server:
  port: 17002
spring:
  application:
    name: firstService
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15 #发呆时间，即服务续约到期时间（缺省为30）
    lease-renewal-interval-in-seconds: 5 #心跳时间，即服务续约间隔时间（90s）
    prefer-ip-address: true #可以 将IP注册到Eureka Server,如果不配置就是机器主机名
  client:
    registry-fetch-interval-seconds: 10 #拉取服务注册信息间隔
    service-url:
      #defaultZone: http://eureka1:1000/eureka/,http://eureka2:1001/eureka/,http://eureka3:1002/eureka/
      defaultZone: http://eureka1:1000/eureka/
    healthcheck:
      enabled: true #健康检查




